new target test-check-clean-force to continue after failing check

diff --git a/GrAL/gral/Makefile.global b/GrAL/gral/Makefile.global
--- a/GrAL/gral/Makefile.global
+++ b/GrAL/gral/Makefile.global
@@ -65,6 +65,14 @@ test-check-clean:
         $(MAKE) test-check-clean GRALROOT=$(GRALROOT) CONFIG=$(GRALROOT)/$$i/mk.config;\
         echo "LEAVING  directory" $$i;cd ..; done)
 
+test-check-clean-force:
+	@set -e; \
+        (for i in $(SUBDIRS); \
+        do cd $(GRALROOT)/$$i;echo 'ENTERING directory' $$i;\
+        $(MAKE) test-check-clean GRALROOT=$(GRALROOT) CONFIG=$(GRALROOT)/$$i/mk.config \
+        || echo ">>>>>>>>>>> FAILED for " $$i " (continuing)";\
+        echo "LEAVING  directory" $$i;cd ..; done)
+
 
 
 # predoc  = generate docs
