csh -> sh

diff --git a/GrAL/sequence/test/bijective-mapping/runtest b/GrAL/sequence/test/bijective-mapping/runtest
--- a/GrAL/sequence/test/bijective-mapping/runtest
+++ b/GrAL/sequence/test/bijective-mapping/runtest
@@ -1,13 +1,16 @@
-#!/bin/csh
-./test-bijective  >& out
-foreach i ( out )
+#!/bin/sh
+./test-bijective  > out 2>&1
+for i in  out 
+do
 /bin/echo "\n"
-diff -w $i $i.exp
-if ($status) then 
-/bin/echo "\t\t\t" ERROR in $i
-else
+if diff -w $i $i.exp
+then 
 /bin/echo "\t\t\t" $i OK
-endif
-end
+status=0
+else
+/bin/echo "\t\t\t" ERROR in $i
+status=1
+fi
+done
 /bin/echo "\n"
-
+exit $status
