*** empty log message ***

diff --git a/GrAL/gral/complex3d/test/iterators/runtest b/GrAL/gral/complex3d/test/iterators/runtest
--- a/GrAL/gral/complex3d/test/iterators/runtest
+++ b/GrAL/gral/complex3d/test/iterators/runtest
@@ -2,9 +2,9 @@
 
 out=out
 
-if ! ./test-boundary-grid  > $out 2>&1
+if ! ./test-complex3d-iterators > $out 2>&1
 then
-    echo "ERROR running test-boundary-grid
+    echo "ERROR running test-complex3d-iterators
 Output was:
 "
 cat $out
@@ -13,7 +13,7 @@ End output
 "
 else
 /bin/echo "\n"
-for i in  out
+for i in  *out
 do
 if diff $i $i.exp
 then 
