*** empty log message ***

diff --git a/GrAL/gral/distributed/test/mpi/runtest b/GrAL/gral/distributed/test/mpi/runtest
--- a/GrAL/gral/distributed/test/mpi/runtest
+++ b/GrAL/gral/distributed/test/mpi/runtest
@@ -5,23 +5,40 @@ rm -f grid.complex2d grid.part
 cp    grid2x2.complex2d grid.complex2d
 cp    grid2x2.p.2x1     grid.part
 
-${MPIRUN} -v -np 2 -machinefile ./mpihosts test-distributed > 2x2.out 2>&1
+if ! ${MPIRUN} -v -np 2 -machinefile ./mpihosts test-distributed > out2x2 2>&1 
+then
+/bin/echo "ERROR running test-distributed!  Output was:
+";
+cat out2x2
+/bin/echo "
+End output
+";
+else
 mv grid.0.out grid2x2.0.out
 mv grid.1.out grid2x2.1.out
 mv dgf.0 dgf2x2.0.out
 mv dgf.1 dgf2x2.1.out
-
+fi
 
 
 rm -f grid.complex2d grid.part
 cp    grid4x2.complex2d grid.complex2d
 cp    grid4x2.p.2x1     grid.part
 
-${MPIRUN} -v -np 2 -machinefile ./mpihosts test-distributed > 4x2.out 2>&1
+if ! ${MPIRUN} -v -np 2 -machinefile ./mpihosts test-distributed > out4x2 2>&1 
+then
+/bin/echo "ERROR running test-distributed!  Output was:
+";
+cat out4x2
+/bin/echo "
+End output
+";
+else
 mv grid.0.out grid4x2.0.out
 mv grid.1.out grid4x2.1.out
 mv dgf.0 dgf4x2.0.out
 mv dgf.1 dgf4x2.1.out
+fi
 
 /bin/echo "\n"
 for i in grid2x2.*.out dgf2x2.?.out grid4x2.*.out dgf4x2.?.out
@@ -33,5 +50,4 @@ else
 /bin/echo "\t\t\t" ERROR in $i
 fi
 done
-/bin/echo "\n"
-
+/bin/echo "\n";
